### ISSUE TITLE
in case you can help

### ISSUE THREAD

**Issue by eoq** [bfrankMS/AzStackHCI#5]
I found your youtube video on setting up the ARB with AKS which perfectly fit my scenario and your AKS+ARB script is very helpful! 

I am on snippet 15 so very close but unfortunately I hit a snag and was wondering if you had any ideas.

If I run the following to setup the networking I get the below error:

`az azurestackhci virtualnetwork create --subscription $SubscriptionId --resource-group $resource_group --extended-location name="/subscriptions/$SubscriptionId/resourceGroups/$resource_group/providers/Microsoft.ExtendedLocation/customLocations/$customloc_name" type="CustomLocation" --location $Location --network-type "Transparent" --name $customLocationNetworkName`

_Command group 'azurestackhci' is experimental and under development. Reference and support levels: https://aka.ms/CLI_refstatus
Deployment failed. Correlation ID: 58671ff5-bf62-4a89-9836-781ccaf3193d. **Supported OS Versions : 23H2 or higher. Node(s) not supported : amdcwazs381,amdcwazs380. : Not Supported**_

I am running 22H2.

In this case the name of the switch ($customLocationNetworkName) is the name of a logical HCI switch I created with New-MocVirtualNetwork. I tried to create the switch with the External switch name instead on the hope it would get farther but got this error:

_**HttpRequestPayloadAPISpecValidationFailed: HTTP request payload failed validation against API specification with one or more errors. Please see details for more information.**_

I am running 0.2.9 of the azurestackhci azure cli extension. (2.57.0 of the azure cli)

Any ideas on how I can progress short of upgrading to 23H2?

Thanks,
Ed

**Comment by eoq** [comment]
fyi, I asked MS support and they confirmed that Azure VM Management is not supported now (as of Feb 15 2024) and we need to move to 23H2 so the error I guess is correct. Instead of trying to hack around it we will do a fresh install of 23H2 (since an upgrade path from 22H2 to 23H2 isn't available yet - as of Mar 2024)

**Comment by bfrankMS** [comment]
Hi,
apologies for the late reply. Correct Azure VM Management (aka ARBridge) was never released on 22H2 and functionality was switched of starting this Februrary - so yes it is deprecated on 22H2.
If you want to do Azure VM Management you need to switch to 23H2. The of it is included in the HCI setup:
![image](https://github.com/bfrankMS/AzStackHCI/assets/41586338/85c53543-4af8-43e6-8608-523ed95ba4f9)
i.e. you would not need these scripts anylonger. In fact they won't work as the az cli for Azure VM Management is different on 23H2

**Comment by Karl-WE** [comment]
Hello Berhard,
yesterday in my lab tried to deploy AKS via WAC. I can do everything but not step 7. Button greyed out to create the AKS cluster. Intentional block? 

I have few customers that cannot upgrade to 22H2 and are not amused about the end of preview of the the ARB, and as it seems AKS, too.

 

 

Best regards,
Karl Wester-Ebbinghaus

Microsoft MVP - Windows Server & Azure Hybrid / Migrate

 

 

 

Von: Bernhard Frank ***@***.***> 
Gesendet: Dienstag, 5. März 2024 10:37
An: bfrankMS/AzStackHCI ***@***.***>
Cc: Subscribed ***@***.***>
Betreff: Re: [bfrankMS/AzStackHCI] in case you can help (Issue #5)

 

Hi,
apologies for the late reply. Correct Azure VM Management (aka ARBridge) was never released on 22H2 and functionality was switched of starting this Februrary - so yes it is deprecated on 22H2.
If you want to do Azure VM Management you need to switch to 23H2. The setup is way easier: i.e. it will be part of the HCI setup:
image.png (view on web) <https://github.com/bfrankMS/AzStackHCI/assets/41586338/85c53543-4af8-43e6-8608-523ed95ba4f9>
